
backend:
  name: github
  repo: lavio-cpu/Samslavio-Site
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Conteúdo do Site"
    files:
      - file: "index.html"
        label: "Página Inicial"
        name: "index"
        fields:
          - { label: "Conteúdo HTML", name: "body", widget: "code", default: "" }
